# 注意：
# xx:
#   yy: true 表示对象{xx:{yy:true}}
# xx:
#   - yy 表示数组 xx=['yy']
#

## Menu
menu:
  Home: /
  Archives: /archives
  About: /about

## Theme  
theme_color:
    theme: '#2ca6cb' 

## index & post
index:
  expand: true    
  excerpt_link: Read More  

## helper
browser_update_tip: true

## Toc
toc:
  article: true   ## show contents in article.
  aside: true 

## RSS
rss: /atom.xml

## Links
links:
  Jurnlee's Blog: http://jurnlee.cc


## Comment
comment:
    disqus:   # enter disqus shortname here
    duoshuo:  # enter duoshuo shortname here
    youyan:   # enter youyan uid here
    facebook: # enter true to enable
    isso:     # enter the domain name of your own comment isso server eg. comments.example.com

## Share 
share: default # options: jiathis, bdshare, addtoany, default
jiathis:
  enable: false ## if you use jiathis as your share tool,the built-in share tool won't be display.
  id:    ## e.g. 1889330 your jiathis ID. 
  tsina: ## e.g. 2176287895 Your weibo id,It will be used in share button.

## statis 
baidu_tongji:
  enable: true
  sitecode: e6d1f421bbc9962127a50488f9ed37d1 ## e.g. e6d1f421bbc9962127a50488f9ed37d1 your baidu tongji site code
cnzz_tongji:
  enable: false
  siteid:    ## e.g. 1253575964 your cnzz tongji site id

## search 
tinysou_search:     ## http://tinysou.com/
  enable: false
  id:  ## e.g. "4ac092ad8d749fdc6293" for your tiny search id

## widgets
widgets: 
  - github-card
  - category
  - tag

## plugins 
plugins: 
  lightgallery: 


less: 
  compress: true
  paths: 
    - source/less